//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANSws.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class anspWMsEntities : DbContext
    {
        public anspWMsEntities()
            : base("name=anspWMsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblTrade> tblTrades { get; set; }
        public virtual DbSet<tblUserGcm> tblUserGcms { get; set; }
        public virtual DbSet<UserWeb> UserWebs { get; set; }
    }
}
