//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANSws.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrade
    {
        public int Id { get; set; }
        public string Client { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Series { get; set; }
        public string InstrumentType { get; set; }
        public string Buy_Sell_Message { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string ExchangeNo { get; set; }
        public string ExchangeName { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> TradeTimestamp { get; set; }
        public string OptionType { get; set; }
        public Nullable<decimal> StrikePrice { get; set; }
        public Nullable<decimal> TradeNumber { get; set; }
        public Nullable<decimal> OrderNumber { get; set; }
    }
}
