//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANSws.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWeb
    {
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public string UserPassword { get; set; }
        public byte UserGroupType { get; set; }
        public string AccountCode { get; set; }
        public bool ActiveStatus { get; set; }
        public bool AllowDn { get; set; }
        public string UserContact { get; set; }
        public string UserEmail { get; set; }
        public string UserAddress { get; set; }
        public Nullable<System.DateTime> LockInTime { get; set; }
        public Nullable<System.DateTime> LockOutTime { get; set; }
        public string LastUserPassword { get; set; }
        public Nullable<System.DateTime> LastPasswordDate { get; set; }
        public short PasswordExpiryDays { get; set; }
        public bool NoPasswordChange { get; set; }
        public string ValidSubAccountList { get; set; }
        public string ValidPermisionList { get; set; }
        public bool AutoFTP { get; set; }
        public string FTPURL { get; set; }
        public string FTPFolder { get; set; }
        public bool LoginStatus { get; set; }
        public string LoginComputer { get; set; }
        public Nullable<System.DateTime> LastLogInTime { get; set; }
        public Nullable<System.DateTime> LastLogOutTime { get; set; }
        public System.DateTime TrxDate { get; set; }
        public bool BXLoginStatus { get; set; }
        public string BXLoginComputer { get; set; }
        public Nullable<System.DateTime> BXLastLogInTime { get; set; }
        public Nullable<System.DateTime> BXLastLogOutTime { get; set; }
        public decimal BXVersion { get; set; }
        public byte BXLicense { get; set; }
        public int SignCount { get; set; }
        public int BXSignCount { get; set; }
        public string DisplayDateFormat { get; set; }
        public string EntryDateFormat { get; set; }
        public byte EditMode { get; set; }
        public byte EditSource { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public short UserId { get; set; }
        public string FileUploadType { get; set; }
        public byte TransComplete { get; set; }
        public byte MyStatus { get; set; }
        public string UserPassword1 { get; set; }
        public string AccountLinkCode { get; set; }
        public string LogComputersList { get; set; }
    }
}
